### ISSUE TITLE
deps: Relax dependency version specifiers

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/pysource-codegen#14]
Same as https://github.com/15r10nk/pysource-minimize/issues/9:

> Poetry has this bad default of adding dependencies to pyproject.toml with the `^` specifier (which by the way is not part of the PEP 508 standard), which depending on the specified version, can be super restrictive, and cause issues in the ecosystem due to resolution conflicts.
It can be seen as a good idea, because Semver promises to protect you from breaking changes, but in practice it does not, and the upper bounds contaminate every downstream projects, without any workaround possible.
A great article that explains the situation much better than I would: https://iscinumpy.dev/post/bound-version-constraints/.
I'd summarize it as: in the Python ecosystem, use upper bounds only if you **know** that the excluded versions will break your code. 
Same thing happens for your development dependencies (higher chances of conflicts during resolution), although these one don't contaminate downstream projects, fortunately.
Similarly `python = "^3.7"` would contaminate every downstream project, forcing them to specify `python-requires = ">=3.7,<4"`, but fortunately enough, most dependency/project managers just ignore this specific upper bound, to prevent exactly that. Poetry does not though.
I'd suggest using `>=` everywhere instead.

**Comment by 15r10nk** [comment]
Again thank you for this issue. It is fixed in 0.4.3
