### ISSUE TITLE
Add license file and metadata

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/pysource-codegen#24]
I recommend adding a `LICENSE` file and some license metadata in pyproject.toml :slightly_smiling_face:

**Comment by 15r10nk** [comment]
Thank you. I fixed this in #25. 

I'm still searching for a project template engine. I tried copier but it did not worked as expected. 

I'm searching for something more strict and where I can test some template configurations (I hope this will not become my next project).

**Comment by pawamoy** [comment]
Thanks! Don't hesitate to share what didn't work for you in a Copier discussion, maybe we have workarounds or solutions :)
